### ISSUE TITLE
TODO list experiments 

### ISSUE THREAD

**Issue by alecabodi** [nickstella/model-fusion#9]
For all base models A, B with: 
architecture {VGG11, ResNet18}, batch size {32, 128, 512}, dataset {MNIST, CIFAR10} 
same initialisation and different initialisation: 

PRELIMINARIES
- [x] compute LMC barrier between them 
- [x] compute solutions sharpness 

BASELINES
- [x] perform and evaluate prediction ensembling 
- [x] perform and evaluate vanilla averaging 

OT FUSION
- [x] align model B: re-evaluate model B_aligned, compute LMC barrier between A and B_aligned
- [x] fuse A and B_aligned: eval ot_fused model 

COMPARISON I 
- [x] compute vanilla avg solution sharpness + eigenspectrum
- [x] compute ot_fusion solution sharpness + eigenspectrum

FINETUNING
- [x] perform finetuning of vanilla avg model with optimal batch size
- [x] perform finetuning of ot_fusion model with optimal batch size 

COMPARISON II 
- [x] compute finetuned vanilla avg solution sharpness and compare with base models 
- [x] compute finetuned ot_fusion solution sharpness and compare with base models
